services:
  fastapi:
    container_name: fastapi
    build: .
    expose:
      - 6000
    networks:
      - SummarEase-Backend-Network
    env_file:
      - ./.env
    volumes:
      - ./gunicorn_conf.py:/keyword_extractor/gunicorn_conf.py:ro
      - ./logs/fastapi/:/var/log/fastapi

  nginx:
    container_name: nginx
    build: ./nginx/
    ports:
      - 1338:80
    networks:
      - SummarEase-Backend-Network
    depends_on:
      - fastapi
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx/:/var/log/nginx/:rw


networks:
  SummarEase-Backend-Network:
    driver: bridge
    external: true