version: '3.8'

services:
  fastapi:
    container_name: fastapi
    build: .
    expose:
      - 6000
    networks:
      - SummarEase-Backend-Network
    env_file:
      - ./.env

  nginx:
    container_name: nginx
    build: ./nginx/
    ports:
      - 1338:80
    networks:
      - SummarEase-Backend-Network
    depends_on:
      - fastapi


networks:
  SummarEase-Backend-Network:
    driver: bridge
    external: true